#!/bin/zsh
#
# Quick shortcut to an editor.
#
# This means that as I travel back and forth between editors, hey, I don't have
# to re-learn any arcane commands. Neat.
#
# USAGE:
#
#   $ e
#   # => opens the current directory in your editor
#
#   $ e .
#   $ e /usr/local
#   # => opens the specified directory in your editor

if [ ! -z "$1" ] && [ -s "$GOPATH/src/$1" ]; then
  $EDITOR "$GOPATH/src/$1"
elif [ -z "$1" ]; then
  $EDITOR .
else
  $EDITOR "$1"
fi
